# -*- mode: python -*-

import sys, os
sys.path.append('../../../isy-academy-common/site_scons')
import python_exercise_helpers

import SCons
try:
	Import('env')
except SCons.Errors.UserError:
	env = Environment()


python_exercise_helpers.run(env, 'test_temperature.py')
python_exercise_helpers.run(env, 'test_generator.py', 'temperature > generated_test4temperature.py', 'generated_test4temperature.py')



