# -*- mode: python -*-

import sys, os
sys.path.append('../../../isy-academy-common/site_scons')
import python_exercise_helpers

import SCons
try:
	Import('env')
except SCons.Errors.UserError:
	env = Environment()


python_exercise_helpers.run(env, 'test_piglatin.py')
python_exercise_helpers.run(env, 'wordcount.py', '--topcount ' + os.path.abspath('alice.txt'))
python_exercise_helpers.run(env, 'test_generator.py', 'piglatin generated_test4piglatin.py', 'generated_test4piglatin.py')


