# -*- mode: python -*-

import sys, os
sys.path.append('../../../isy-academy-common/site_scons')
import python_exercise_helpers

import SCons
try:
	Import('env')
except SCons.Errors.UserError:
	env = Environment()


python_exercise_helpers.run(env, 'point.py')
python_exercise_helpers.run(env, 'shapes.py')
python_exercise_helpers.run(env, 'test_generator.py', 'shapes shapes_test.py', 'shapes_test.py')


env.SConscript('outlets_basic/SConstruct')
env.SConscript('outlets_advanced/SConstruct')

