# -*- mode: python -*-

import sys, os
sys.path.append('../../../../isy-academy-common/site_scons')
import python_exercise_helpers
from python_exercise_helpers import run_with_automatic_redirect  # less ambiguous then the other 'run' so import directly

import SCons
try:
	Import('env')
except SCons.Errors.UserError:
	env = Environment()


cameras = os.path.abspath("snelheidscameras_met_lus_120601.csv")
default_params = ' '.join(('--cameras', cameras))

run_with_automatic_redirect(env, 'query_cameras.py', default_params + ' --cameras-on-road E40')
run_with_automatic_redirect(env, 'query_cameras.py', default_params + ' --cameras-in-city Oostende')


