# -*- mode: python -*-

import sys, os
sys.path.append('../../../isy-academy-common/site_scons')
import python_exercise_helpers

import SCons
try:
	Import('env')
except SCons.Errors.UserError:
	env = Environment()


python_exercise_helpers.run(env, 'dict_inverse.py')
python_exercise_helpers.run(env, 'number_tester.py')
python_exercise_helpers.run(env, 'palindrome.py')
python_exercise_helpers.run(env, 'transpose.py')

